const FETCH_CURRENCY_REQUEST = 'FETCH_CURRENCY_REQUEST';
const FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS';
const FETCH_CURRENCY_FAILURE = 'FETCH_CURRENCY_FAILURE';
const SELECT_CURRENCY = 'SELECT_CURRENCY';

export {
  FETCH_CURRENCY_FAILURE,
  FETCH_CURRENCY_REQUEST,
  FETCH_CURRENCY_SUCCESS,
  SELECT_CURRENCY,
};
